apiVersion: v1
kind: Service
metadata:
  name: kubia-loadbalancer
spec:
  selector:
    app: hello-kube
  type: LoadBalancer
  externalIPs:
    - 192.168.56.11
  ports:
    - port: 80
      targetPort: 3000