apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate # Recreate or RollingUpdate. Default is RollingUpdate
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - image: lamkhoi1304/hello-kube:v1
          name: hello-app
          ports:
            - containerPort: 3000
              protocol: TCP
          # Zero downtime
          # Readiness check
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          # Prestop hook
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 15"]

---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000