apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  containers:
    - image: luksa/fortune
      name: html-generator
      volumeMounts:
        - name: html  # volume html is mounted at /var/htdocs in html-generator container
          mountPath: /var/htdocs
    
    - image: nginx:alpine
      name: webserver
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: html  # volume html is mounted at /usr/share/nginx/html in webserver container
          mountPath: /usr/share/nginx/html
          readOnly: true
  volumes:          # define volumes
    - name: html    # name of the volume
      emptyDir: {}  # define type is emptyDir

# Script in luksa/fortune image
#!/bin/bash
# trap "exit" SIGINT
# mkdir /var/htdocs

# while:
# do
#   echo $(date) Writing fortune to /var/htdocs/index.html
#   /usr/game/fortune > /var/htdocs/index.html
#   sleep 10
# done