apiVersion: v1
kind: Pod
metadata:
  name: gitrepo
spec:
  containers:
    - image: nginx:alpine
      name: webserver
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
  
  volumes:
    - name: html
      gitRepo:                                                          # gitrepo volume
        repository: https://github.com/luksa/kubia-website-example.git  # The volume will clone this git repository
        revision: master                                                # master branch
        directory: .                                                    # clone into the root dir of the volume